#!/usr/bin/env python3
"""
Sprint 1 batched component generation — sonar-pro single call.
Generates: triage strip, confidence badges, monitor strip, signal panel, overview page template.
Each component has 2-3 variants for review.
Output: docs/generated/sprint1-components-draft.html
"""
import os, sys, json, requests, base64, subprocess
from datetime import datetime, timezone

PPLX_API_KEY = os.environ.get("PPLX_API_KEY")
GH_TOKEN     = os.environ.get("GH_TOKEN")
REPO         = "asym-intel/asym-intel-main"
OUTPUT_PATH  = "docs/generated/sprint1-components-draft.html"
MODEL        = "sonar-pro"

if not PPLX_API_KEY:
    print("ERROR: PPLX_API_KEY not set"); sys.exit(1)
if not GH_TOKEN:
    print("ERROR: GH_TOKEN not set"); sys.exit(1)

# ── Read reference files from repo ────────────────────────────────────────────
def read_repo_file(path, max_chars=None):
    r = subprocess.run(
        ["gh", "api", f"/repos/{REPO}/contents/{path}", "--jq", ".content"],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        print(f"WARNING: could not read {path}")
        return ""
    content = base64.b64decode(r.stdout.strip()).decode("utf-8")
    if max_chars:
        return content[:max_chars]
    return content

print("Reading reference files...")
base_css           = read_repo_file("static/monitors/shared/css/base.css", max_chars=4000)
colour_registry    = read_repo_file("docs/ux/colour-registry.md", max_chars=3000)
badge_spec         = read_repo_file("docs/ux/badge-spec.md")
section_naming     = read_repo_file("docs/ux/section-naming-registry.md", max_chars=2000)
overview_brief     = read_repo_file("docs/ux/monitor-overview-brief.md", max_chars=3000)

# Check what we got
for name, content in [
    ("base.css", base_css),
    ("colour-registry.md", colour_registry),
    ("badge-spec.md", badge_spec),
    ("section-naming-registry.md", section_naming),
    ("monitor-overview-brief.md", overview_brief),
]:
    status = f"{len(content)} chars" if content else "EMPTY/FAILED"
    print(f"  {name}: {status}")

# ── Build prompt ──────────────────────────────────────────────────────────────
TODAY = datetime.now(timezone.utc).strftime("%Y-%m-%d")

PROMPT = f"""You are an expert front-end developer building shared HTML/CSS components for a multi-monitor intelligence platform called Asymmetric Intelligence (asym-intel.info).

Your task: produce ONE complete, self-contained HTML file that demonstrates all 5 Sprint 1 shared components, each with 2 variants for design review.

## Critical output rules
- Return ONLY valid HTML — no markdown code fences, no prose before or after
- The file must be renderable in a browser without any external files except Fontshare
- All CSS in a single <style> block in <head>
- No inline styles — all styling via CSS classes
- Use `overflow-x: clip` — NEVER `overflow-x: hidden`
- Use `rgba()` for tints — NEVER `color-mix()` (browser compatibility)
- Font: Satoshi via Fontshare CDN — @import url('https://api.fontshare.com/v2/css?f[]=satoshi@300,400,500,700&display=swap');
- Use ONLY the CSS variables defined in the base.css reference below (replicate them in a :root block)
- Responsive: desktop (>900px), tablet (600–900px), mobile (<600px)
- Begin the file with this exact comment: <!-- Sprint 1 Components Draft | Generated by sonar-pro | {TODAY} | STATUS: DRAFT -->

## Reference: base.css variables (replicate these in :root)

```css
{base_css}
```

## Reference: colour registry

```markdown
{colour_registry}
```

## Reference: badge spec

```markdown
{badge_spec}
```

## Reference: section naming registry (nav tab order)

```markdown
{section_naming}
```

## Reference: monitor overview brief

```markdown
{overview_brief}
```

---

## File structure to produce

ONE HTML file with this exact structure:

```html
<!-- Sprint 1 Components Draft | Generated by sonar-pro | {TODAY} | STATUS: DRAFT -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sprint 1 Components Draft</title>
  <!-- Satoshi font -->
  <!-- All :root variables from base.css -->
  <!-- All component CSS -->
  <!-- Demo page layout CSS -->
</head>
<body>
  <!-- Page header -->
  <!-- Component 1: Triage Strip (variants A and B) -->
  <!-- Component 2: Confidence Badge (variants A and B) -->
  <!-- Component 3: Monitor Strip (variants A and B) -->
  <!-- Component 4: Signal Panel (variants A and B) -->
  <!-- Component 5: Monitor Overview Template (variants A and B) -->
</body>
</html>
```

Each variant must be wrapped in:
```html
<section class="demo-section">
  <div class="demo-section__header">
    <h2 class="demo-section__title">Component Name — Variant A (Label)</h2>
    <p class="demo-section__note">Implementation note: what makes this variant different and when to choose it.</p>
  </div>
  <!-- component HTML here -->
</section>
```

---

## COMPONENT 1 — TRIAGE STRIP

A horizontal strip appearing at the top of every monitor dashboard, giving immediate situational awareness in 4 zones.

### CSS classes to define:
- `.triage-strip` — outer container, flex row on desktop
- `.triage-zone` — each of the 4 zones, flex column
- `.triage-zone--kpi` — KPI zone (left)
- `.triage-zone--signal` — Lead Signal zone
- `.triage-zone--snapshot` — Structural snapshot zone
- `.triage-zone--delta` — Delta zone (right)
- `.triage-kpi-value` — large metric number, --text-2xl or --text-3xl, bold
- `.triage-kpi-label` — small label below number, --text-xs, --color-text-muted
- `.triage-signal-headline` — signal headline, --text-sm, --color-text
- `.triage-snapshot-chips` — chips container, flex wrap
- `.triage-chip` — individual status chip, small pill
- `.triage-delta-item` — a single delta item with severity badge
- Responsive: 4 columns desktop, 2×2 tablet, stacked mobile

Zones separated by subtle dividers (1px --color-border). Strip background: --color-surface. Padding: --space-4. Border-bottom: 1px solid --color-border.

### Variant A — Minimal
Implementation note: Minimal variant for monitors with sparse data or as a low-visual-weight option. KPI + Lead Signal + 2 chips + 1 delta item. Zones have no background fill — just dividers. Use when the dashboard header already has strong colour presence.

Demo data (WDM — Water/Democratic monitor):
- KPI: "15" label "Rapid Decay countries"
- Signal: "Hungary 6 days from pivotal vote; US executive–SCOTUS confrontation enters new phase"
- Chips: ["5 Recovery", "13 Watch List"]
- Delta: [("Hungary", critical)]

### Variant B — Standard
Implementation note: Full 4-zone layout for most monitors. KPI zone + Lead Signal zone + Structural snapshot zone (3 chips) + Delta zone (2 items). Each zone has a subtle left border accent in --monitor-accent for visual anchoring. Use as the default triage strip variant.

Demo data (WDM):
- KPI: "15" label "Rapid Decay countries"  
- Signal: "Hungary 6 days from pivotal vote; US executive–SCOTUS confrontation enters new phase"
- Chips: ["5 Recovery", "13 Watch List", "DEMOCRATIC STRESS"]
- Delta: [("Hungary", critical), ("United States", high)]
- Set --monitor-accent to #61a5d2 (WDM) via a scoped style on the demo container

---

## COMPONENT 2 — CONFIDENCE BADGE

Confidence badges are visually distinct from severity badges: outline only, no fill.

### CSS classes to define (using rgba() ONLY — no oklch, no color-mix):
```css
.badge-confidence {{
  display: inline-flex;
  align-items: center;
  padding: 0.15em 0.55em;
  border: 1px solid rgba(107, 102, 96, 0.35);  /* --color-text-muted at ~35% */
  border-radius: 99px;
  font-size: var(--text-xs);
  font-weight: 500;
  color: var(--color-text-muted);
  background: transparent;
  white-space: nowrap;
}}
.badge-confidence--confirmed  {{ border-color: rgba(5, 150, 105, 0.5); color: var(--positive); }}
.badge-confidence--high        {{ border-color: rgba(107, 102, 96, 0.5); }}
.badge-confidence--assessed    {{ border-color: rgba(107, 102, 96, 0.35); }}
.badge-confidence--possible    {{ border-color: rgba(107, 102, 96, 0.2); color: var(--color-text-faint); }}
```

NEVER use --critical, --high, --moderate, --contested on confidence badges.

Also define severity badges for contrast:
```css
.severity-badge {{ display: inline-flex; align-items: center; padding: 0.15em 0.55em; border-radius: 99px; font-size: var(--text-xs); font-weight: 600; white-space: nowrap; }}
.severity-badge--critical {{ background: var(--critical-bg); color: var(--critical); }}
.severity-badge--high {{ background: var(--high-bg); color: var(--high); }}
.severity-badge--moderate {{ background: var(--moderate-bg); color: var(--moderate); }}
.severity-badge--positive {{ background: var(--positive-bg); color: var(--positive); }}
.severity-badge--contested {{ background: var(--contested-bg); color: var(--contested); }}
```

### Variant A — Pure Outline
Implementation note: Completely neutral — 1px border, transparent fill, --color-text-muted text with no colour tint. All confidence levels look similar except for slight opacity changes. Use when you want confidence badges to recede visually and not draw attention.

Show all 4 levels side by side: Confirmed · High · Assessed · Possible
Also show a finding card with both severity badge + confidence badge together.

### Variant B — Tinted Outline
Implementation note: Adds a subtle colour tint to the border only for Confirmed (success-green border) and Possible (very faint border). No filled background at any level. Use when you want to reward Confirmed findings with a slightly more positive visual signal without competing with severity badges.

Show all 4 levels side by side, then a comparison table showing Severity (filled) vs Confidence (outline) badges for all levels.

---

## COMPONENT 3 — MONITOR STRIP

The cross-monitor navigation strip showing all 7 monitors. Order: GMM · SCEM · FCW · AGM · WDM · ESA · ERM

Accent colours (use as rgba() tints and borders — NEVER as solid backgrounds unless active):
- GMM: #22a0aa
- SCEM: #dc2626
- FCW: #38bdf8
- AGM: #7a39bb
- WDM: #61a5d2
- ESA: #5b8db0
- ERM: #4caf7d

### CSS classes to define:
- `.monitor-strip` — container, flex row, overflow-x: clip (NOT hidden), --color-surface background
- `.monitor-strip__item` — each monitor tab/pill
- `.monitor-strip__item--active` — active state
- `.monitor-strip__dot` — small colour dot indicator (used in Variant B)

### Variant A — Pill Row
Implementation note: 7 coloured pills in a horizontally scrollable row. Each pill: monitor abbreviation, accent colour as border + text. Active pill: filled accent background with white text. Use for compact navigation where monitor identity is the primary affordance.

HTML for each pill (note: active pill is WDM in this demo):
```html
<nav class="monitor-strip monitor-strip--pills">
  <a class="monitor-strip__item" data-monitor="gmm" style="--accent: #22a0aa">GMM</a>
  <a class="monitor-strip__item" data-monitor="scem" style="--accent: #dc2626">SCEM</a>
  <a class="monitor-strip__item" data-monitor="fcw" style="--accent: #38bdf8">FCW</a>
  <a class="monitor-strip__item" data-monitor="agm" style="--accent: #7a39bb">AGM</a>
  <a class="monitor-strip__item monitor-strip__item--active" data-monitor="wdm" style="--accent: #61a5d2">WDM</a>
  <a class="monitor-strip__item" data-monitor="esa" style="--accent: #5b8db0">ESA</a>
  <a class="monitor-strip__item" data-monitor="erm" style="--accent: #4caf7d">ERM</a>
</nav>
```
Use CSS custom property `var(--accent)` for pill border colour and text; active: background var(--accent), color white.
Since no inline styles are allowed in the final component, use data attributes and generated CSS rules for each monitor slug in the demo.

Actually: define CSS rules for each monitor slug using attribute selectors:
```css
.monitor-strip__item[data-monitor="gmm"] {{ --accent: #22a0aa; }}
.monitor-strip__item[data-monitor="scem"] {{ --accent: #dc2626; }}
/* etc */
.monitor-strip__item {{ border-color: var(--accent); color: var(--accent); }}
.monitor-strip__item--active {{ background: var(--accent); color: white; }}
```

### Variant B — Compact Label Row
Implementation note: 7 text links with a small coloured dot (4px circle) indicator as the sole colour element. More text-forward, less colour-heavy. Active state: dot grows or fills, underline in accent. Use when the page already has strong monitor-colour presence and you want the strip to feel lighter.

Each item: [dot] Monitor Full Name or abbreviation. Active item has solid dot + accent underline.

---

## COMPONENT 4 — SIGNAL PANEL

The Lead Signal panel appears on every monitor dashboard. Shows the week's primary analytical signal.

### CSS classes to define:
- `.signal-panel` — outer container
- `.signal-panel--compact` — Variant A modifier
- `.signal-panel--accent` — Variant B modifier  
- `.signal-panel__headline` — the signal headline, --text-lg or --text-xl, medium/semibold
- `.signal-panel__body` — supporting paragraph, --text-sm, --color-text-secondary
- `.signal-panel__meta` — metadata row (issue number, date, confidence), --text-xs, --color-text-faint

### Variant A — Compact
Implementation note: White panel background (--color-surface), 3px accent-coloured left border (--monitor-accent), headline in --color-text, body in --color-text-secondary. Minimal visual weight. Use as the default for monitors where the triage strip already has colour presence.

Demo data (ERM):
- Headline: "Amazon dieback rate accelerates; AMOC slowdown confirms new precursor threshold crossing"
- Body: "The Amazon tipping point probability has increased by 12pp this week as new satellite data confirms accelerated deforestation rates. AMOC slowdown measurements crossed the Boers et al. threshold, triggering a new precursor classification."
- Meta: "Issue 4 · W/E 6 April 2026 · Confidence: Assessed"
- Set --monitor-accent to #4caf7d for the demo

### Variant B — Accent Background
Implementation note: Full accent-tinted background (--monitor-accent-bg via rgba), with a stronger left border in --monitor-accent. When accent is dark (e.g. SCEM red #dc2626), ALL text must be white or near-white. For lighter accents, use --color-text. Use for monitors where the signal panel is the dominant hero element.

Demo data (ERM — same data as Variant A):
- Same content as above
- Use rgba(76, 175, 125, 0.10) as background tint
- Headline in --color-text (ERM green is light enough)
- Also show a second example with SCEM red accent where text goes white/near-white

---

## COMPONENT 5 — MONITOR OVERVIEW PAGE TEMPLATE

A full-page template for the monitor overview/about page. Uses ERM as the demo monitor.

Monitor data for demo:
- Monitor: Environmental Risks Monitor (ERM)
- Abbreviation: ERM
- Accent: #4caf7d  
- Accent bg tint: rgba(76, 175, 125, 0.08)
- Issue: Issue 4, W/E 6 April 2026
- Lead signal: "Amazon dieback rate accelerates; AMOC slowdown confirms new precursor threshold crossing"
- Stats: 6/9 planetary boundaries breached, 4 risk regions, AMOC warning active
- Strapline: "Tracking planetary boundary conditions, climate tipping points, and ecological risk cascades."

Canonical section order per overview brief:
1. Hero (monitor identity + strapline + current issue CTA)
2. Latest Issue (featured card with lead signal)
3. How to use (brief guide)
4. What it tracks (domain scope)
5. This week at a glance (key numbers)
6. Why different (methodology note)
7. Cross-monitor connections

Right rail (sticky on desktop, collapsed on mobile):
- Section list (anchor nav)
- Summary block (3 key stats)
- Action buttons: Dashboard · Latest Issue · Living Knowledge · Subscribe

### CSS classes to define:
- `.overview-layout` — two-column grid (main + right rail) on desktop, single column mobile
- `.overview-hero` — hero band
- `.overview-hero--plain` — Variant A modifier
- `.overview-hero--rich` — Variant B modifier
- `.overview-hero__eyebrow` — "MONITOR OVERVIEW" label above title
- `.overview-hero__title` — monitor name, --text-2xl or --text-3xl
- `.overview-hero__strapline` — strapline, --text-base
- `.overview-hero__dot` — small accent dot (Variant B)
- `.overview-section` — each content section
- `.overview-section__heading` — section heading, --text-lg
- `.overview-latest-card` — featured latest issue card
- `.overview-latest-card--accented` — Variant B modifier with accent left rule
- `.overview-stat-block` — the "at a glance" stat block
- `.overview-stat` — individual stat
- `.overview-stat__value` — big number
- `.overview-stat__label` — stat label
- `.overview-rail` — right rail container
- `.overview-rail__section-list` — section anchor nav list
- `.overview-rail__action` — action button
- `.overview-pill-row` — small pill row (Variant B only)

### Variant A — Minimal
Implementation note: Lighter colour presence, more neutral. Hero band uses --color-surface background with a subtle bottom border. Cards use only a subtle top border in --monitor-accent (3px). No gradient, no tint backgrounds in the hero. Monitor identity is expressed through typography and the minimal accent border. Use when the page feels too dense with colour or when the monitor has a high-severity accent (SCEM red).

Structure:
```
[Hero: plain white/surface background, title, strapline, "View Issue 4 →" CTA]
[Main content: sections 1-7 with card borders only]
[Right rail: sticky, nav list + stat summary + action buttons]
```

### Variant B — Rich
Implementation note: As per ERM mockup direction. Hero band with accent-tinted gradient (rgba tint from left, fading right) + 4px left accent rule. Monitor abbreviation dot in header. Eyebrow text in --monitor-accent. Latest issue card with 3px left rule in accent. Pill row showing "6/9 boundaries breached" chips in accent-soft palette. Use for monitors where the brief encourages stronger visual identity (ERM, GMM, AGM).

Structure:
```
[Hero: accent gradient tint + left rule, eyebrow in accent, monitor dot, rich CTA block]
[Latest card: accent left rule, signal headline prominent]
[Right rail: same as Variant A but with accent-coloured action buttons]
[Stat block: accent-tinted background for "at a glance" numbers]
[Pill row: "6/9 boundaries · 4 regions · AMOC warning" chips in accent-soft]
```

---

## Demo page layout CSS

Add these demo layout classes (NOT part of the component library — just for the review page):

```css
body {{
  font-family: var(--font-sans);
  background: var(--color-bg);
  color: var(--color-text);
  margin: 0;
  padding: 0;
}}
.demo-page-header {{
  background: var(--color-surface);
  border-bottom: 1px solid var(--color-border);
  padding: var(--space-6) var(--space-8);
}}
.demo-page-header h1 {{ font-size: var(--text-xl); font-weight: 700; margin: 0 0 var(--space-1); }}
.demo-page-header p {{ font-size: var(--text-sm); color: var(--color-text-muted); margin: 0; }}
.demo-toc {{
  padding: var(--space-4) var(--space-8);
  background: var(--color-bg-alt);
  border-bottom: 1px solid var(--color-border);
  display: flex;
  gap: var(--space-4);
  flex-wrap: wrap;
}}
.demo-toc a {{ font-size: var(--text-sm); color: var(--color-text-muted); text-decoration: none; }}
.demo-toc a:hover {{ color: var(--color-text); }}
.demo-component-group {{
  margin: var(--space-8) 0;
}}
.demo-component-group__heading {{
  font-size: var(--text-lg);
  font-weight: 700;
  color: var(--color-text);
  padding: var(--space-4) var(--space-8);
  border-bottom: 2px solid var(--color-border);
  margin: 0;
  background: var(--color-surface);
}}
.demo-section {{
  padding: var(--space-6) var(--space-8);
  border-bottom: 1px solid var(--color-border);
}}
.demo-section__header {{
  margin-bottom: var(--space-4);
}}
.demo-section__title {{
  font-size: var(--text-base);
  font-weight: 600;
  margin: 0 0 var(--space-2);
  color: var(--color-text);
}}
.demo-section__note {{
  font-size: var(--text-xs);
  color: var(--color-text-muted);
  margin: 0;
  padding: var(--space-2) var(--space-3);
  background: var(--color-bg-alt);
  border-left: 3px solid var(--color-border);
  border-radius: 0 var(--radius) var(--radius) 0;
}}
```

---

Now produce the complete HTML file. Remember:
- ONE file, all CSS in <head>, no inline styles
- All 5 components × 2 variants = 10 demo sections
- Realistic mock data in every demo
- Implementation notes above each variant
- base.css variables replicated in :root
- File starts with the required comment block
"""

# Count components in prompt
components = [
    "COMPONENT 1 — TRIAGE STRIP",
    "COMPONENT 2 — CONFIDENCE BADGE",
    "COMPONENT 3 — MONITOR STRIP",
    "COMPONENT 4 — SIGNAL PANEL",
    "COMPONENT 5 — MONITOR OVERVIEW",
]
print(f"\nPrompt length: {len(PROMPT)} chars")
print(f"Components in prompt: {len(components)}")
for c in components:
    present = c in PROMPT
    print(f"  {'✓' if present else '✗'} {c}")

# ── Call sonar-pro (single call) ───────────────────────────────────────────────
print(f"\nCalling {MODEL} (single batched call)...")
resp = requests.post(
    "https://api.perplexity.ai/chat/completions",
    headers={
        "Authorization": f"Bearer {PPLX_API_KEY}",
        "Content-Type":  "application/json"
    },
    json={
        "model":       MODEL,
        "messages":    [{"role": "user", "content": PROMPT}],
        "temperature": 0.15,
        "max_tokens":  16000,
    },
    timeout=300
)

if resp.status_code != 200:
    print(f"ERROR: API returned {resp.status_code}: {resp.text[:500]}")
    sys.exit(1)

output = resp.json()["choices"][0]["message"]["content"]
print(f"Raw output: {len(output)} chars")

# ── Strip markdown fences if model wrapped output ──────────────────────────────
stripped = output.strip()
if stripped.startswith("```"):
    lines = stripped.split("\n")
    # Remove first line (``` or ```html) and last line if it's ```
    end_idx = -1 if lines[-1].strip() == "```" else len(lines)
    stripped = "\n".join(lines[1:end_idx])
    print(f"Stripped markdown fences → {len(stripped)} chars")

# Ensure the required comment block is present
if "Sprint 1 Components Draft" not in stripped:
    header_comment = f"<!-- Sprint 1 Components Draft | Generated by sonar-pro | {TODAY} | STATUS: DRAFT -->\n"
    stripped = header_comment + stripped
    print("Prepended required comment block")

output_html = stripped
print(f"Final output: {len(output_html)} chars, {len(output_html.splitlines())} lines")

# ── Sanity check: verify all 5 components appear ──────────────────────────────
checks = [
    ("Triage Strip",     "triage-strip"),
    ("Confidence Badge", "badge-confidence"),
    ("Monitor Strip",    "monitor-strip"),
    ("Signal Panel",     "signal-panel"),
    ("Overview Template","overview-layout"),
]
print("\nComponent presence check:")
all_present = True
for label, marker in checks:
    present = marker in output_html
    print(f"  {'✓' if present else '✗'} {label} ({marker})")
    if not present:
        all_present = False

if not all_present:
    print("WARNING: Some components may be missing from output — review HTML before promoting.")

# ── Commit to repo ─────────────────────────────────────────────────────────────
print(f"\nCommitting to {REPO}/{OUTPUT_PATH} ...")
encoded = base64.b64encode(output_html.encode("utf-8")).decode("ascii")

# Check if file already exists (need SHA for update)
existing = subprocess.run(
    ["gh", "api", f"/repos/{REPO}/contents/{OUTPUT_PATH}", "--jq", ".sha"],
    capture_output=True, text=True
)

commit_msg = (
    f"feat(generated): sprint1-components-draft — sonar-pro {TODAY} "
    f"({len(output_html)} chars, 5 components × 2 variants)"
)

payload = {
    "message": commit_msg,
    "content": encoded
}
if existing.returncode == 0 and existing.stdout.strip():
    sha = existing.stdout.strip().strip('"')
    if sha:
        payload["sha"] = sha
        print(f"  Updating existing file (SHA: {sha[:8]})")
    else:
        print("  Creating new file")
else:
    print("  Creating new file")

import tempfile, pathlib
tmp = pathlib.Path(tempfile.mktemp(suffix=".json"))
tmp.write_text(json.dumps(payload))

result = subprocess.run(
    ["gh", "api", f"/repos/{REPO}/contents/{OUTPUT_PATH}",
     "--method", "PUT", "--input", str(tmp),
     "--jq", ".commit.sha[:8]"],
    capture_output=True, text=True
)

if result.returncode == 0:
    commit_sha = result.stdout.strip()
    print(f"\n✓ Committed to {OUTPUT_PATH}")
    print(f"  Commit SHA: {commit_sha}")
    print(f"  URL: https://github.com/{REPO}/blob/main/{OUTPUT_PATH}")
else:
    print(f"ERROR committing: {result.stderr.strip()[:400]}")
    sys.exit(1)

tmp.unlink(missing_ok=True)

# ── Summary ────────────────────────────────────────────────────────────────────
print(f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Sprint 1 batch generation complete
  Model:       {MODEL}
  Output:      {OUTPUT_PATH}
  HTML size:   {len(output_html):,} chars / {len(output_html.splitlines())} lines
  Components:  5 × 2 variants = 10 demo sections
  Commit:      {commit_sha}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""")
